/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ApproveAndCallFallBackInterface extends ethers.utils.Interface {
  functions: {
    "receiveApproval(address,uint256,address,bytes)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "receiveApproval",
    values: [string, BigNumberish, string, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "receiveApproval",
    data: BytesLike
  ): Result;

  events: {};
}

export class ApproveAndCallFallBack extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ApproveAndCallFallBackInterface;

  functions: {
    receiveApproval(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "receiveApproval(address,uint256,address,bytes)"(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  receiveApproval(
    from: string,
    tokens: BigNumberish,
    token: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "receiveApproval(address,uint256,address,bytes)"(
    from: string,
    tokens: BigNumberish,
    token: string,
    data: BytesLike,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    receiveApproval(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;

    "receiveApproval(address,uint256,address,bytes)"(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    receiveApproval(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "receiveApproval(address,uint256,address,bytes)"(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    receiveApproval(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "receiveApproval(address,uint256,address,bytes)"(
      from: string,
      tokens: BigNumberish,
      token: string,
      data: BytesLike,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
