/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer } from "ethers";
import { Provider } from "@ethersproject/providers";

import type { ApproveAndCallFallBack } from "./ApproveAndCallFallBack";

export class ApproveAndCallFallBackFactory {
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ApproveAndCallFallBack {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ApproveAndCallFallBack;
  }
}

const _abi = [
  {
    constant: false,
    inputs: [
      {
        name: "from",
        type: "address",
      },
      {
        name: "tokens",
        type: "uint256",
      },
      {
        name: "token",
        type: "address",
      },
      {
        name: "data",
        type: "bytes",
      },
    ],
    name: "receiveApproval",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
];
