/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface LotteryInterface extends ethers.utils.Interface {
  functions: {
    "isLotteryLive()": FunctionFragment;
    "declareWinner()": FunctionFragment;
    "lotteryName()": FunctionFragment;
    "manager()": FunctionFragment;
    "addressIndexes(uint256)": FunctionFragment;
    "getPlayer(address)": FunctionFragment;
    "potSize()": FunctionFragment;
    "endAt()": FunctionFragment;
    "getPlayers()": FunctionFragment;
    "setLotteryStatus(bool)": FunctionFragment;
    "createdAt()": FunctionFragment;
    "coinsRequired()": FunctionFragment;
    "getWinningPrice()": FunctionFragment;
    "winner()": FunctionFragment;
    "creatorFee()": FunctionFragment;
    "participate(string,uint256)": FunctionFragment;
    "lotteryBag(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "isLotteryLive",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "declareWinner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryName",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "manager", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "addressIndexes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getPlayer", values: [string]): string;
  encodeFunctionData(functionFragment: "potSize", values?: undefined): string;
  encodeFunctionData(functionFragment: "endAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setLotteryStatus",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "createdAt", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "coinsRequired",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getWinningPrice",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "winner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "creatorFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "participate",
    values: [string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lotteryBag",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "isLotteryLive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "declareWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lotteryName",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "manager", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addressIndexes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "potSize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "endAt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getPlayers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLotteryStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "createdAt", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "coinsRequired",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getWinningPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "winner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "creatorFee", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "participate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lotteryBag", data: BytesLike): Result;

  events: {
    "WinnerDeclared(string)": EventFragment;
    "PlayerParticipated(string,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "WinnerDeclared"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "PlayerParticipated"): EventFragment;
}

export class Lottery extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: LotteryInterface;

  functions: {
    isLotteryLive(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "isLotteryLive()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    declareWinner(overrides?: Overrides): Promise<ContractTransaction>;

    "declareWinner()"(overrides?: Overrides): Promise<ContractTransaction>;

    lotteryName(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "lotteryName()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    manager(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "manager()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    addressIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "addressIndexes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    getPlayer(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;

    "getPlayer(address)"(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;

    potSize(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "potSize()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    endAt(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "endAt()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    getPlayers(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;

    "getPlayers()"(overrides?: CallOverrides): Promise<{
      0: string[];
    }>;

    setLotteryStatus(
      status: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setLotteryStatus(bool)"(
      status: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    createdAt(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "createdAt()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    coinsRequired(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "coinsRequired()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    getWinningPrice(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "getWinningPrice()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    winner(overrides?: CallOverrides): Promise<{
      name: string;
      ticketCount: BigNumber;
      index: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    "winner()"(overrides?: CallOverrides): Promise<{
      name: string;
      ticketCount: BigNumber;
      index: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    creatorFee(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    "creatorFee()"(overrides?: CallOverrides): Promise<{
      0: BigNumber;
    }>;

    participate(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "participate(string,uint256)"(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    lotteryBag(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;

    "lotteryBag(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
    }>;
  };

  isLotteryLive(overrides?: CallOverrides): Promise<boolean>;

  "isLotteryLive()"(overrides?: CallOverrides): Promise<boolean>;

  declareWinner(overrides?: Overrides): Promise<ContractTransaction>;

  "declareWinner()"(overrides?: Overrides): Promise<ContractTransaction>;

  lotteryName(overrides?: CallOverrides): Promise<string>;

  "lotteryName()"(overrides?: CallOverrides): Promise<string>;

  manager(overrides?: CallOverrides): Promise<string>;

  "manager()"(overrides?: CallOverrides): Promise<string>;

  addressIndexes(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  "addressIndexes(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  getPlayer(
    playerAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: BigNumber;
  }>;

  "getPlayer(address)"(
    playerAddress: string,
    overrides?: CallOverrides
  ): Promise<{
    0: string;
    1: BigNumber;
  }>;

  potSize(overrides?: CallOverrides): Promise<BigNumber>;

  "potSize()"(overrides?: CallOverrides): Promise<BigNumber>;

  endAt(overrides?: CallOverrides): Promise<string>;

  "endAt()"(overrides?: CallOverrides): Promise<string>;

  getPlayers(overrides?: CallOverrides): Promise<string[]>;

  "getPlayers()"(overrides?: CallOverrides): Promise<string[]>;

  setLotteryStatus(
    status: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setLotteryStatus(bool)"(
    status: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  createdAt(overrides?: CallOverrides): Promise<string>;

  "createdAt()"(overrides?: CallOverrides): Promise<string>;

  coinsRequired(overrides?: CallOverrides): Promise<BigNumber>;

  "coinsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

  getWinningPrice(overrides?: CallOverrides): Promise<BigNumber>;

  "getWinningPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

  winner(overrides?: CallOverrides): Promise<{
    name: string;
    ticketCount: BigNumber;
    index: BigNumber;
    0: string;
    1: BigNumber;
    2: BigNumber;
  }>;

  "winner()"(overrides?: CallOverrides): Promise<{
    name: string;
    ticketCount: BigNumber;
    index: BigNumber;
    0: string;
    1: BigNumber;
    2: BigNumber;
  }>;

  creatorFee(overrides?: CallOverrides): Promise<BigNumber>;

  "creatorFee()"(overrides?: CallOverrides): Promise<BigNumber>;

  participate(
    playerName: string,
    tickets: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "participate(string,uint256)"(
    playerName: string,
    tickets: BigNumberish,
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  lotteryBag(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  "lotteryBag(uint256)"(
    arg0: BigNumberish,
    overrides?: CallOverrides
  ): Promise<string>;

  callStatic: {
    isLotteryLive(overrides?: CallOverrides): Promise<boolean>;

    "isLotteryLive()"(overrides?: CallOverrides): Promise<boolean>;

    declareWinner(overrides?: CallOverrides): Promise<void>;

    "declareWinner()"(overrides?: CallOverrides): Promise<void>;

    lotteryName(overrides?: CallOverrides): Promise<string>;

    "lotteryName()"(overrides?: CallOverrides): Promise<string>;

    manager(overrides?: CallOverrides): Promise<string>;

    "manager()"(overrides?: CallOverrides): Promise<string>;

    addressIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    "addressIndexes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;

    getPlayer(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;

    "getPlayer(address)"(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<{
      0: string;
      1: BigNumber;
    }>;

    potSize(overrides?: CallOverrides): Promise<BigNumber>;

    "potSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    endAt(overrides?: CallOverrides): Promise<string>;

    "endAt()"(overrides?: CallOverrides): Promise<string>;

    getPlayers(overrides?: CallOverrides): Promise<string[]>;

    "getPlayers()"(overrides?: CallOverrides): Promise<string[]>;

    setLotteryStatus(status: boolean, overrides?: CallOverrides): Promise<void>;

    "setLotteryStatus(bool)"(
      status: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    createdAt(overrides?: CallOverrides): Promise<string>;

    "createdAt()"(overrides?: CallOverrides): Promise<string>;

    coinsRequired(overrides?: CallOverrides): Promise<BigNumber>;

    "coinsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWinningPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getWinningPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    winner(overrides?: CallOverrides): Promise<{
      name: string;
      ticketCount: BigNumber;
      index: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    "winner()"(overrides?: CallOverrides): Promise<{
      name: string;
      ticketCount: BigNumber;
      index: BigNumber;
      0: string;
      1: BigNumber;
      2: BigNumber;
    }>;

    creatorFee(overrides?: CallOverrides): Promise<BigNumber>;

    "creatorFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    participate(
      playerName: string,
      tickets: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    "participate(string,uint256)"(
      playerName: string,
      tickets: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    lotteryBag(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    "lotteryBag(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<string>;
  };

  filters: {
    WinnerDeclared(name: null): EventFilter;

    PlayerParticipated(name: null, ticketCount: null): EventFilter;
  };

  estimateGas: {
    isLotteryLive(overrides?: CallOverrides): Promise<BigNumber>;

    "isLotteryLive()"(overrides?: CallOverrides): Promise<BigNumber>;

    declareWinner(overrides?: Overrides): Promise<BigNumber>;

    "declareWinner()"(overrides?: Overrides): Promise<BigNumber>;

    lotteryName(overrides?: CallOverrides): Promise<BigNumber>;

    "lotteryName()"(overrides?: CallOverrides): Promise<BigNumber>;

    manager(overrides?: CallOverrides): Promise<BigNumber>;

    "manager()"(overrides?: CallOverrides): Promise<BigNumber>;

    addressIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "addressIndexes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPlayer(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "getPlayer(address)"(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    potSize(overrides?: CallOverrides): Promise<BigNumber>;

    "potSize()"(overrides?: CallOverrides): Promise<BigNumber>;

    endAt(overrides?: CallOverrides): Promise<BigNumber>;

    "endAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    getPlayers(overrides?: CallOverrides): Promise<BigNumber>;

    "getPlayers()"(overrides?: CallOverrides): Promise<BigNumber>;

    setLotteryStatus(
      status: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "setLotteryStatus(bool)"(
      status: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    createdAt(overrides?: CallOverrides): Promise<BigNumber>;

    "createdAt()"(overrides?: CallOverrides): Promise<BigNumber>;

    coinsRequired(overrides?: CallOverrides): Promise<BigNumber>;

    "coinsRequired()"(overrides?: CallOverrides): Promise<BigNumber>;

    getWinningPrice(overrides?: CallOverrides): Promise<BigNumber>;

    "getWinningPrice()"(overrides?: CallOverrides): Promise<BigNumber>;

    winner(overrides?: CallOverrides): Promise<BigNumber>;

    "winner()"(overrides?: CallOverrides): Promise<BigNumber>;

    creatorFee(overrides?: CallOverrides): Promise<BigNumber>;

    "creatorFee()"(overrides?: CallOverrides): Promise<BigNumber>;

    participate(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "participate(string,uint256)"(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    lotteryBag(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "lotteryBag(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    isLotteryLive(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isLotteryLive()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    declareWinner(overrides?: Overrides): Promise<PopulatedTransaction>;

    "declareWinner()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    lotteryName(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "lotteryName()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    manager(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "manager()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    addressIndexes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "addressIndexes(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPlayer(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "getPlayer(address)"(
      playerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    potSize(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "potSize()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    endAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "endAt()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getPlayers(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getPlayers()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setLotteryStatus(
      status: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setLotteryStatus(bool)"(
      status: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    createdAt(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "createdAt()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    coinsRequired(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "coinsRequired()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getWinningPrice(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "getWinningPrice()"(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    winner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "winner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    creatorFee(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "creatorFee()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    participate(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "participate(string,uint256)"(
      playerName: string,
      tickets: BigNumberish,
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    lotteryBag(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "lotteryBag(uint256)"(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
